apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aspnetcore-razorapp-{{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetcore-razorapp-{{.Release.Name}}
    spec:
      containers:
      - name: aspnetcore-razorapp-{{.Release.Name}}
        image: bradygaster/aspnetcore-razorapp:latest
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: aspnetcore-razorapp-{{.Release.Name}}