apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: aspnetcore
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: bradyg@microsoft.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}