apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-worker-{{.Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcore-worker-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: netcore-worker-{{.Release.Name}}
    spec:
      containers:
      - name: netcore-worker-{{.Release.Name}}
        image: bradygaster/netcore-worker:latest
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: DELAY
          value: "5000"